// app/components/cvgen/utils/Nationalities.ts

export interface Nationality {
  code: string;
  label: string;
  flag?: string;
  separator?: boolean;
}

export type SupportedLocale = 'fr' | 'en';

// Country code to flag emoji
export const countryFlags: Record<string, string> = {
  FR: '🇫🇷', IT: '🇮🇹', BE: '🇧🇪', CH: '🇨🇭', MA: '🇲🇦', TN: '🇹🇳', DZ: '🇩🇿',
  AF: '🇦🇫', ZA: '🇿🇦', AL: '🇦🇱', DE: '🇩🇪', US: '🇺🇸', AD: '🇦🇩', AO: '🇦🇴',
  SA: '🇸🇦', AR: '🇦🇷', AM: '🇦🇲', AU: '🇦🇺', AT: '🇦🇹', BR: '🇧🇷', GB: '🇬🇧',
  BG: '🇧🇬', KH: '🇰🇭', CM: '🇨🇲', CA: '🇨🇦', CL: '🇨🇱', CN: '🇨🇳', CO: '🇨🇴',
  CG: '🇨🇬', KR: '🇰🇷', HR: '🇭🇷', CU: '🇨🇺', DK: '🇩🇰', EG: '🇪🇬', AE: '🇦🇪',
  EC: '🇪🇨', ES: '🇪🇸', EE: '🇪🇪', FI: '🇫🇮', GE: '🇬🇪', GH: '🇬🇭', GR: '🇬🇷',
  GT: '🇬🇹', HT: '🇭🇹', HU: '🇭🇺', IN: '🇮🇳', ID: '🇮🇩', IQ: '🇮🇶', IR: '🇮🇷',
  IE: '🇮🇪', IS: '🇮🇸', IL: '🇮🇱', CI: '🇨🇮', JP: '🇯🇵', JO: '🇯🇴', KZ: '🇰🇿',
  KE: '🇰🇪', LB: '🇱🇧', LY: '🇱🇾', LU: '🇱🇺', MK: '🇲🇰', MY: '🇲🇾', ML: '🇲🇱',
  MX: '🇲🇽', MC: '🇲🇨', MN: '🇲🇳', ME: '🇲🇪', NL: '🇳🇱', NZ: '🇳🇿', NE: '🇳🇪',
  NG: '🇳🇬', NO: '🇳🇴', PK: '🇵🇰', PE: '🇵🇪', PH: '🇵🇭', PL: '🇵🇱', PT: '🇵🇹',
  QA: '🇶🇦', RO: '🇷🇴', RU: '🇷🇺', SN: '🇸🇳', RS: '🇷🇸', SG: '🇸🇬', SK: '🇸🇰',
  SI: '🇸🇮', SE: '🇸🇪', TW: '🇹🇼', TD: '🇹🇩', CZ: '🇨🇿', TH: '🇹🇭', TR: '🇹🇷',
  UA: '🇺🇦', UY: '🇺🇾', VE: '🇻🇪', VN: '🇻🇳', CR: '🇨🇷', ET: '🇪🇹',
};

export const getFlag = (code: string): string => countryFlags[code] || '🏳️';

export const nationalities: Record<SupportedLocale, Nationality[]> = {
  fr: [
    // Nationalités prioritaires
    { code: 'FR', label: 'Française' },
    { code: 'IT', label: 'Italienne' },
    { code: 'BE', label: 'Belge' },
    { code: 'CH', label: 'Suisse' },
    { code: 'MA', label: 'Marocaine' },
    { code: 'TN', label: 'Tunisienne' },
    { code: 'DZ', label: 'Algérienne' },
    // Séparateur
    { code: '---', label: '───────────────', separator: true },
    // Autres nationalités (ordre alphabétique)
    { code: 'AF', label: 'Afghane' },
    { code: 'ZA', label: 'Africaine du Sud' },
    { code: 'AL', label: 'Albanaise' },
    { code: 'DE', label: 'Allemande' },
    { code: 'US', label: 'Américaine' },
    { code: 'AD', label: 'Andorrane' },
    { code: 'AO', label: 'Angolaise' },
    { code: 'SA', label: 'Arabie Saoudienne' },
    { code: 'AR', label: 'Argentine' },
    { code: 'AM', label: 'Arménienne' },
    { code: 'AU', label: 'Australienne' },
    { code: 'AT', label: 'Autrichienne' },
    { code: 'BR', label: 'Brésilienne' },
    { code: 'GB', label: 'Britannique' },
    { code: 'BG', label: 'Bulgare' },
    { code: 'KH', label: 'Cambodgienne' },
    { code: 'CM', label: 'Camerounaise' },
    { code: 'CA', label: 'Canadienne' },
    { code: 'CL', label: 'Chilienne' },
    { code: 'CN', label: 'Chinoise' },
    { code: 'CO', label: 'Colombienne' },
    { code: 'CG', label: 'Congolaise' },
    { code: 'KR', label: 'Coréenne du Sud' },
    { code: 'HR', label: 'Croate' },
    { code: 'CU', label: 'Cubaine' },
    { code: 'DK', label: 'Danoise' },
    { code: 'EG', label: 'Égyptienne' },
    { code: 'AE', label: 'Émiratie' },
    { code: 'EC', label: 'Équatorienne' },
    { code: 'ES', label: 'Espagnole' },
    { code: 'EE', label: 'Estonienne' },
    { code: 'FI', label: 'Finlandaise' },
    { code: 'GE', label: 'Géorgienne' },
    { code: 'GH', label: 'Ghanéenne' },
    { code: 'GR', label: 'Grecque' },
    { code: 'GT', label: 'Guatémaltèque' },
    { code: 'HT', label: 'Haïtienne' },
    { code: 'HU', label: 'Hongroise' },
    { code: 'IN', label: 'Indienne' },
    { code: 'ID', label: 'Indonésienne' },
    { code: 'IQ', label: 'Irakienne' },
    { code: 'IR', label: 'Iranienne' },
    { code: 'IE', label: 'Irlandaise' },
    { code: 'IS', label: 'Islandaise' },
    { code: 'IL', label: 'Israélienne' },
    { code: 'CI', label: 'Ivoirienne' },
    { code: 'JP', label: 'Japonaise' },
    { code: 'JO', label: 'Jordanienne' },
    { code: 'KZ', label: 'Kazakhe' },
    { code: 'KE', label: 'Kényane' },
    { code: 'LB', label: 'Libanaise' },
    { code: 'LY', label: 'Libyenne' },
    { code: 'LU', label: 'Luxembourgeoise' },
    { code: 'MK', label: 'Macédonienne' },
    { code: 'MY', label: 'Malaisienne' },
    { code: 'ML', label: 'Malienne' },
    { code: 'MX', label: 'Mexicaine' },
    { code: 'MC', label: 'Monégasque' },
    { code: 'MN', label: 'Mongole' },
    { code: 'ME', label: 'Monténégrine' },
    { code: 'NL', label: 'Néerlandaise' },
    { code: 'NZ', label: 'Néo-Zélandaise' },
    { code: 'NE', label: 'Nigérienne' },
    { code: 'NG', label: 'Nigériane' },
    { code: 'NO', label: 'Norvégienne' },
    { code: 'PK', label: 'Pakistanaise' },
    { code: 'PE', label: 'Péruvienne' },
    { code: 'PH', label: 'Philippine' },
    { code: 'PL', label: 'Polonaise' },
    { code: 'PT', label: 'Portugaise' },
    { code: 'QA', label: 'Qatarienne' },
    { code: 'RO', label: 'Roumaine' },
    { code: 'RU', label: 'Russe' },
    { code: 'SN', label: 'Sénégalaise' },
    { code: 'RS', label: 'Serbe' },
    { code: 'SG', label: 'Singapourienne' },
    { code: 'SK', label: 'Slovaque' },
    { code: 'SI', label: 'Slovène' },
    { code: 'SE', label: 'Suédoise' },
    { code: 'TW', label: 'Taïwanaise' },
    { code: 'TD', label: 'Tchadienne' },
    { code: 'CZ', label: 'Tchèque' },
    { code: 'TH', label: 'Thaïlandaise' },
    { code: 'TR', label: 'Turque' },
    { code: 'UA', label: 'Ukrainienne' },
    { code: 'UY', label: 'Uruguayenne' },
    { code: 'VE', label: 'Vénézuélienne' },
    { code: 'VN', label: 'Vietnamienne' },
  ],
  en: [
    // Priority nationalities
    { code: 'FR', label: 'French' },
    { code: 'IT', label: 'Italian' },
    { code: 'BE', label: 'Belgian' },
    { code: 'CH', label: 'Swiss' },
    { code: 'MA', label: 'Moroccan' },
    { code: 'TN', label: 'Tunisian' },
    { code: 'DZ', label: 'Algerian' },
    // Separator
    { code: '---', label: '───────────────', separator: true },
    // Other nationalities (alphabetical order)
    { code: 'AF', label: 'Afghan' },
    { code: 'AL', label: 'Albanian' },
    { code: 'US', label: 'American' },
    { code: 'AD', label: 'Andorran' },
    { code: 'AO', label: 'Angolan' },
    { code: 'AR', label: 'Argentinian' },
    { code: 'AM', label: 'Armenian' },
    { code: 'AU', label: 'Australian' },
    { code: 'AT', label: 'Austrian' },
    { code: 'BR', label: 'Brazilian' },
    { code: 'GB', label: 'British' },
    { code: 'BG', label: 'Bulgarian' },
    { code: 'KH', label: 'Cambodian' },
    { code: 'CM', label: 'Cameroonian' },
    { code: 'CA', label: 'Canadian' },
    { code: 'TD', label: 'Chadian' },
    { code: 'CL', label: 'Chilean' },
    { code: 'CN', label: 'Chinese' },
    { code: 'CO', label: 'Colombian' },
    { code: 'CG', label: 'Congolese' },
    { code: 'CR', label: 'Costa Rican' },
    { code: 'HR', label: 'Croatian' },
    { code: 'CU', label: 'Cuban' },
    { code: 'CZ', label: 'Czech' },
    { code: 'DK', label: 'Danish' },
    { code: 'NL', label: 'Dutch' },
    { code: 'EC', label: 'Ecuadorian' },
    { code: 'EG', label: 'Egyptian' },
    { code: 'AE', label: 'Emirati' },
    { code: 'EE', label: 'Estonian' },
    { code: 'ET', label: 'Ethiopian' },
    { code: 'FI', label: 'Finnish' },
    { code: 'GE', label: 'Georgian' },
    { code: 'DE', label: 'German' },
    { code: 'GH', label: 'Ghanaian' },
    { code: 'GR', label: 'Greek' },
    { code: 'GT', label: 'Guatemalan' },
    { code: 'HT', label: 'Haitian' },
    { code: 'HU', label: 'Hungarian' },
    { code: 'IS', label: 'Icelandic' },
    { code: 'IN', label: 'Indian' },
    { code: 'ID', label: 'Indonesian' },
    { code: 'IR', label: 'Iranian' },
    { code: 'IQ', label: 'Iraqi' },
    { code: 'IE', label: 'Irish' },
    { code: 'IL', label: 'Israeli' },
    { code: 'CI', label: 'Ivorian' },
    { code: 'JP', label: 'Japanese' },
    { code: 'JO', label: 'Jordanian' },
    { code: 'KZ', label: 'Kazakh' },
    { code: 'KE', label: 'Kenyan' },
    { code: 'KR', label: 'Korean' },
    { code: 'LB', label: 'Lebanese' },
    { code: 'LY', label: 'Libyan' },
    { code: 'LU', label: 'Luxembourgish' },
    { code: 'MK', label: 'Macedonian' },
    { code: 'MY', label: 'Malaysian' },
    { code: 'ML', label: 'Malian' },
    { code: 'MX', label: 'Mexican' },
    { code: 'MC', label: 'Monacan' },
    { code: 'MN', label: 'Mongolian' },
    { code: 'ME', label: 'Montenegrin' },
    { code: 'NZ', label: 'New Zealander' },
    { code: 'NE', label: 'Nigerien' },
    { code: 'NG', label: 'Nigerian' },
    { code: 'NO', label: 'Norwegian' },
    { code: 'PK', label: 'Pakistani' },
    { code: 'PE', label: 'Peruvian' },
    { code: 'PH', label: 'Philippine' },
    { code: 'PL', label: 'Polish' },
    { code: 'PT', label: 'Portuguese' },
    { code: 'QA', label: 'Qatari' },
    { code: 'RO', label: 'Romanian' },
    { code: 'RU', label: 'Russian' },
    { code: 'SA', label: 'Saudi' },
    { code: 'SN', label: 'Senegalese' },
    { code: 'RS', label: 'Serbian' },
    { code: 'SG', label: 'Singaporean' },
    { code: 'SK', label: 'Slovak' },
    { code: 'SI', label: 'Slovenian' },
    { code: 'ZA', label: 'South African' },
    { code: 'ES', label: 'Spanish' },
    { code: 'SE', label: 'Swedish' },
    { code: 'TW', label: 'Taiwanese' },
    { code: 'TH', label: 'Thai' },
    { code: 'TR', label: 'Turkish' },
    { code: 'UA', label: 'Ukrainian' },
    { code: 'UY', label: 'Uruguayan' },
    { code: 'VE', label: 'Venezuelan' },
    { code: 'VN', label: 'Vietnamese' },
  ],
};
