// app/components/cvgen/utils/Nationalities.ts

export interface Nationality {
  code: string;
  label: string;        // Default/feminine form (for selection display)
  labelMale?: string;   // Male form (for languages with gender)
  separator?: boolean;
}

export type SupportedLocale = 'fr' | 'en' | 'it';

// Country code to flag emoji
export const countryFlags: Record<string, string> = {
  FR: '🇫🇷', IT: '🇮🇹', BE: '🇧🇪', CH: '🇨🇭', MA: '🇲🇦', TN: '🇹🇳', DZ: '🇩🇿',
  AF: '🇦🇫', ZA: '🇿🇦', AL: '🇦🇱', DE: '🇩🇪', US: '🇺🇸', AD: '🇦🇩', AO: '🇦🇴',
  SA: '🇸🇦', AR: '🇦🇷', AM: '🇦🇲', AU: '🇦🇺', AT: '🇦🇹', BR: '🇧🇷', GB: '🇬🇧',
  BG: '🇧🇬', KH: '🇰🇭', CM: '🇨🇲', CA: '🇨🇦', CL: '🇨🇱', CN: '🇨🇳', CO: '🇨🇴',
  CG: '🇨🇬', KR: '🇰🇷', HR: '🇭🇷', CU: '🇨🇺', DK: '🇩🇰', EG: '🇪🇬', AE: '🇦🇪',
  EC: '🇪🇨', ES: '🇪🇸', EE: '🇪🇪', FI: '🇫🇮', GE: '🇬🇪', GH: '🇬🇭', GR: '🇬🇷',
  GT: '🇬🇹', HT: '🇭🇹', HU: '🇭🇺', IN: '🇮🇳', ID: '🇮🇩', IQ: '🇮🇶', IR: '🇮🇷',
  IE: '🇮🇪', IS: '🇮🇸', IL: '🇮🇱', CI: '🇨🇮', JP: '🇯🇵', JO: '🇯🇴', KZ: '🇰🇿',
  KE: '🇰🇪', LB: '🇱🇧', LY: '🇱🇾', LU: '🇱🇺', MK: '🇲🇰', MY: '🇲🇾', ML: '🇲🇱',
  MX: '🇲🇽', MC: '🇲🇨', MN: '🇲🇳', ME: '🇲🇪', NL: '🇳🇱', NZ: '🇳🇿', NE: '🇳🇪',
  NG: '🇳🇬', NO: '🇳🇴', PK: '🇵🇰', PE: '🇵🇪', PH: '🇵🇭', PL: '🇵🇱', PT: '🇵🇹',
  QA: '🇶🇦', RO: '🇷🇴', RU: '🇷🇺', SN: '🇸🇳', RS: '🇷🇸', SG: '🇸🇬', SK: '🇸🇰',
  SI: '🇸🇮', SE: '🇸🇪', TW: '🇹🇼', TD: '🇹🇩', CZ: '🇨🇿', TH: '🇹🇭', TR: '🇹🇷',
  UA: '🇺🇦', UY: '🇺🇾', VE: '🇻🇪', VN: '🇻🇳', CR: '🇨🇷', ET: '🇪🇹',
};

export const getFlag = (code: string): string => countryFlags[code] || '🏳️';

/**
 * Get nationality label based on gender and locale
 * @param code - Country code (e.g., 'FR', 'IT')
 * @param sex - 'male' or 'female'
 * @param locale - 'fr', 'en', or 'it'
 */
export function getNationalityLabel(code: string, sex: string, locale: string): string {
  const localeKey = (locale === 'fr' || locale === 'en' || locale === 'it') ? locale : 'en';
  const nationalityList = nationalities[localeKey];
  const nationality = nationalityList.find(n => n.code === code);
  
  if (!nationality) return code;
  
  // For English, no gender distinction
  if (locale === 'en') {
    return nationality.label;
  }
  
  // For French and Italian, use male form if available and sex is male
  if (sex === 'male' && nationality.labelMale) {
    return nationality.labelMale;
  }
  
  return nationality.label;
}

export const nationalities: Record<SupportedLocale, Nationality[]> = {
  fr: [
    // Nationalités prioritaires
    { code: 'FR', label: 'Française', labelMale: 'Français' },
    { code: 'IT', label: 'Italienne', labelMale: 'Italien' },
    { code: 'BE', label: 'Belge' }, // Pas de changement
    { code: 'CH', label: 'Suisse' }, // Pas de changement
    { code: 'MA', label: 'Marocaine', labelMale: 'Marocain' },
    { code: 'TN', label: 'Tunisienne', labelMale: 'Tunisien' },
    { code: 'DZ', label: 'Algérienne', labelMale: 'Algérien' },
    // Séparateur
    { code: '---', label: '───────────────', separator: true },
    // Autres nationalités (ordre alphabétique)
    { code: 'AF', label: 'Afghane', labelMale: 'Afghan' },
    { code: 'ZA', label: 'Sud-Africaine', labelMale: 'Sud-Africain' },
    { code: 'AL', label: 'Albanaise', labelMale: 'Albanais' },
    { code: 'DE', label: 'Allemande', labelMale: 'Allemand' },
    { code: 'US', label: 'Américaine', labelMale: 'Américain' },
    { code: 'AD', label: 'Andorrane', labelMale: 'Andorran' },
    { code: 'AO', label: 'Angolaise', labelMale: 'Angolais' },
    { code: 'SA', label: 'Saoudienne', labelMale: 'Saoudien' },
    { code: 'AR', label: 'Argentine', labelMale: 'Argentin' },
    { code: 'AM', label: 'Arménienne', labelMale: 'Arménien' },
    { code: 'AU', label: 'Australienne', labelMale: 'Australien' },
    { code: 'AT', label: 'Autrichienne', labelMale: 'Autrichien' },
    { code: 'BR', label: 'Brésilienne', labelMale: 'Brésilien' },
    { code: 'GB', label: 'Britannique' }, // Pas de changement
    { code: 'BG', label: 'Bulgare' }, // Pas de changement
    { code: 'KH', label: 'Cambodgienne', labelMale: 'Cambodgien' },
    { code: 'CM', label: 'Camerounaise', labelMale: 'Camerounais' },
    { code: 'CA', label: 'Canadienne', labelMale: 'Canadien' },
    { code: 'CL', label: 'Chilienne', labelMale: 'Chilien' },
    { code: 'CN', label: 'Chinoise', labelMale: 'Chinois' },
    { code: 'CO', label: 'Colombienne', labelMale: 'Colombien' },
    { code: 'CG', label: 'Congolaise', labelMale: 'Congolais' },
    { code: 'KR', label: 'Sud-Coréenne', labelMale: 'Sud-Coréen' },
    { code: 'HR', label: 'Croate' }, // Pas de changement
    { code: 'CU', label: 'Cubaine', labelMale: 'Cubain' },
    { code: 'DK', label: 'Danoise', labelMale: 'Danois' },
    { code: 'EG', label: 'Égyptienne', labelMale: 'Égyptien' },
    { code: 'AE', label: 'Émiratie', labelMale: 'Émirati' },
    { code: 'EC', label: 'Équatorienne', labelMale: 'Équatorien' },
    { code: 'ES', label: 'Espagnole', labelMale: 'Espagnol' },
    { code: 'EE', label: 'Estonienne', labelMale: 'Estonien' },
    { code: 'FI', label: 'Finlandaise', labelMale: 'Finlandais' },
    { code: 'GE', label: 'Géorgienne', labelMale: 'Géorgien' },
    { code: 'GH', label: 'Ghanéenne', labelMale: 'Ghanéen' },
    { code: 'GR', label: 'Grecque', labelMale: 'Grec' },
    { code: 'GT', label: 'Guatémaltèque' }, // Pas de changement
    { code: 'HT', label: 'Haïtienne', labelMale: 'Haïtien' },
    { code: 'HU', label: 'Hongroise', labelMale: 'Hongrois' },
    { code: 'IN', label: 'Indienne', labelMale: 'Indien' },
    { code: 'ID', label: 'Indonésienne', labelMale: 'Indonésien' },
    { code: 'IQ', label: 'Irakienne', labelMale: 'Irakien' },
    { code: 'IR', label: 'Iranienne', labelMale: 'Iranien' },
    { code: 'IE', label: 'Irlandaise', labelMale: 'Irlandais' },
    { code: 'IS', label: 'Islandaise', labelMale: 'Islandais' },
    { code: 'IL', label: 'Israélienne', labelMale: 'Israélien' },
    { code: 'CI', label: 'Ivoirienne', labelMale: 'Ivoirien' },
    { code: 'JP', label: 'Japonaise', labelMale: 'Japonais' },
    { code: 'JO', label: 'Jordanienne', labelMale: 'Jordanien' },
    { code: 'KZ', label: 'Kazakhe' }, // Pas de changement
    { code: 'KE', label: 'Kényane', labelMale: 'Kényan' },
    { code: 'LB', label: 'Libanaise', labelMale: 'Libanais' },
    { code: 'LY', label: 'Libyenne', labelMale: 'Libyen' },
    { code: 'LU', label: 'Luxembourgeoise', labelMale: 'Luxembourgeois' },
    { code: 'MK', label: 'Macédonienne', labelMale: 'Macédonien' },
    { code: 'MY', label: 'Malaisienne', labelMale: 'Malaisien' },
    { code: 'ML', label: 'Malienne', labelMale: 'Malien' },
    { code: 'MX', label: 'Mexicaine', labelMale: 'Mexicain' },
    { code: 'MC', label: 'Monégasque' }, // Pas de changement
    { code: 'MN', label: 'Mongole' }, // Pas de changement
    { code: 'ME', label: 'Monténégrine', labelMale: 'Monténégrin' },
    { code: 'NL', label: 'Néerlandaise', labelMale: 'Néerlandais' },
    { code: 'NZ', label: 'Néo-Zélandaise', labelMale: 'Néo-Zélandais' },
    { code: 'NE', label: 'Nigérienne', labelMale: 'Nigérien' },
    { code: 'NG', label: 'Nigériane', labelMale: 'Nigérian' },
    { code: 'NO', label: 'Norvégienne', labelMale: 'Norvégien' },
    { code: 'PK', label: 'Pakistanaise', labelMale: 'Pakistanais' },
    { code: 'PE', label: 'Péruvienne', labelMale: 'Péruvien' },
    { code: 'PH', label: 'Philippine', labelMale: 'Philippin' },
    { code: 'PL', label: 'Polonaise', labelMale: 'Polonais' },
    { code: 'PT', label: 'Portugaise', labelMale: 'Portugais' },
    { code: 'QA', label: 'Qatarienne', labelMale: 'Qatarien' },
    { code: 'RO', label: 'Roumaine', labelMale: 'Roumain' },
    { code: 'RU', label: 'Russe' }, // Pas de changement
    { code: 'SN', label: 'Sénégalaise', labelMale: 'Sénégalais' },
    { code: 'RS', label: 'Serbe' }, // Pas de changement
    { code: 'SG', label: 'Singapourienne', labelMale: 'Singapourien' },
    { code: 'SK', label: 'Slovaque' }, // Pas de changement
    { code: 'SI', label: 'Slovène' }, // Pas de changement
    { code: 'SE', label: 'Suédoise', labelMale: 'Suédois' },
    { code: 'TW', label: 'Taïwanaise', labelMale: 'Taïwanais' },
    { code: 'TD', label: 'Tchadienne', labelMale: 'Tchadien' },
    { code: 'CZ', label: 'Tchèque' }, // Pas de changement
    { code: 'TH', label: 'Thaïlandaise', labelMale: 'Thaïlandais' },
    { code: 'TR', label: 'Turque', labelMale: 'Turc' },
    { code: 'UA', label: 'Ukrainienne', labelMale: 'Ukrainien' },
    { code: 'UY', label: 'Uruguayenne', labelMale: 'Uruguayen' },
    { code: 'VE', label: 'Vénézuélienne', labelMale: 'Vénézuélien' },
    { code: 'VN', label: 'Vietnamienne', labelMale: 'Vietnamien' },
  ],
  en: [
    // Priority nationalities - No gender in English
    { code: 'FR', label: 'French' },
    { code: 'IT', label: 'Italian' },
    { code: 'BE', label: 'Belgian' },
    { code: 'CH', label: 'Swiss' },
    { code: 'MA', label: 'Moroccan' },
    { code: 'TN', label: 'Tunisian' },
    { code: 'DZ', label: 'Algerian' },
    // Separator
    { code: '---', label: '───────────────', separator: true },
    // Other nationalities (alphabetical order)
    { code: 'AF', label: 'Afghan' },
    { code: 'AL', label: 'Albanian' },
    { code: 'US', label: 'American' },
    { code: 'AD', label: 'Andorran' },
    { code: 'AO', label: 'Angolan' },
    { code: 'AR', label: 'Argentinian' },
    { code: 'AM', label: 'Armenian' },
    { code: 'AU', label: 'Australian' },
    { code: 'AT', label: 'Austrian' },
    { code: 'BR', label: 'Brazilian' },
    { code: 'GB', label: 'British' },
    { code: 'BG', label: 'Bulgarian' },
    { code: 'KH', label: 'Cambodian' },
    { code: 'CM', label: 'Cameroonian' },
    { code: 'CA', label: 'Canadian' },
    { code: 'TD', label: 'Chadian' },
    { code: 'CL', label: 'Chilean' },
    { code: 'CN', label: 'Chinese' },
    { code: 'CO', label: 'Colombian' },
    { code: 'CG', label: 'Congolese' },
    { code: 'CR', label: 'Costa Rican' },
    { code: 'HR', label: 'Croatian' },
    { code: 'CU', label: 'Cuban' },
    { code: 'CZ', label: 'Czech' },
    { code: 'DK', label: 'Danish' },
    { code: 'NL', label: 'Dutch' },
    { code: 'EC', label: 'Ecuadorian' },
    { code: 'EG', label: 'Egyptian' },
    { code: 'AE', label: 'Emirati' },
    { code: 'EE', label: 'Estonian' },
    { code: 'ET', label: 'Ethiopian' },
    { code: 'FI', label: 'Finnish' },
    { code: 'GE', label: 'Georgian' },
    { code: 'DE', label: 'German' },
    { code: 'GH', label: 'Ghanaian' },
    { code: 'GR', label: 'Greek' },
    { code: 'GT', label: 'Guatemalan' },
    { code: 'HT', label: 'Haitian' },
    { code: 'HU', label: 'Hungarian' },
    { code: 'IS', label: 'Icelandic' },
    { code: 'IN', label: 'Indian' },
    { code: 'ID', label: 'Indonesian' },
    { code: 'IR', label: 'Iranian' },
    { code: 'IQ', label: 'Iraqi' },
    { code: 'IE', label: 'Irish' },
    { code: 'IL', label: 'Israeli' },
    { code: 'CI', label: 'Ivorian' },
    { code: 'JP', label: 'Japanese' },
    { code: 'JO', label: 'Jordanian' },
    { code: 'KZ', label: 'Kazakh' },
    { code: 'KE', label: 'Kenyan' },
    { code: 'KR', label: 'South Korean' },
    { code: 'LB', label: 'Lebanese' },
    { code: 'LY', label: 'Libyan' },
    { code: 'LU', label: 'Luxembourgish' },
    { code: 'MK', label: 'Macedonian' },
    { code: 'MY', label: 'Malaysian' },
    { code: 'ML', label: 'Malian' },
    { code: 'MX', label: 'Mexican' },
    { code: 'MC', label: 'Monacan' },
    { code: 'MN', label: 'Mongolian' },
    { code: 'ME', label: 'Montenegrin' },
    { code: 'NZ', label: 'New Zealander' },
    { code: 'NE', label: 'Nigerien' },
    { code: 'NG', label: 'Nigerian' },
    { code: 'NO', label: 'Norwegian' },
    { code: 'PK', label: 'Pakistani' },
    { code: 'PE', label: 'Peruvian' },
    { code: 'PH', label: 'Filipino' },
    { code: 'PL', label: 'Polish' },
    { code: 'PT', label: 'Portuguese' },
    { code: 'QA', label: 'Qatari' },
    { code: 'RO', label: 'Romanian' },
    { code: 'RU', label: 'Russian' },
    { code: 'SA', label: 'Saudi' },
    { code: 'SN', label: 'Senegalese' },
    { code: 'RS', label: 'Serbian' },
    { code: 'SG', label: 'Singaporean' },
    { code: 'SK', label: 'Slovak' },
    { code: 'SI', label: 'Slovenian' },
    { code: 'ZA', label: 'South African' },
    { code: 'ES', label: 'Spanish' },
    { code: 'SE', label: 'Swedish' },
    { code: 'TW', label: 'Taiwanese' },
    { code: 'TH', label: 'Thai' },
    { code: 'TR', label: 'Turkish' },
    { code: 'UA', label: 'Ukrainian' },
    { code: 'UY', label: 'Uruguayan' },
    { code: 'VE', label: 'Venezuelan' },
    { code: 'VN', label: 'Vietnamese' },
  ],
  it: [
    // Nazionalità prioritarie
    { code: 'FR', label: 'Francese' },
    { code: 'IT', label: 'Italiana', labelMale: 'Italiano' },
    { code: 'BE', label: 'Belga' },
    { code: 'CH', label: 'Svizzera', labelMale: 'Svizzero' },
    { code: 'MA', label: 'Marocchina', labelMale: 'Marocchino' },
    { code: 'TN', label: 'Tunisina', labelMale: 'Tunisino' },
    { code: 'DZ', label: 'Algerina', labelMale: 'Algerino' },
    // Separatore
    { code: '---', label: '───────────────', separator: true },
    // Altre nazionalità (ordine alfabetico)
    { code: 'AF', label: 'Afghana', labelMale: 'Afghano' },
    { code: 'ZA', label: 'Sudafricana', labelMale: 'Sudafricano' },
    { code: 'AL', label: 'Albanese' },
    { code: 'DE', label: 'Tedesca', labelMale: 'Tedesco' },
    { code: 'US', label: 'Americana', labelMale: 'Americano' },
    { code: 'AD', label: 'Andorrana', labelMale: 'Andorrano' },
    { code: 'AO', label: 'Angolana', labelMale: 'Angolano' },
    { code: 'SA', label: 'Saudita' },
    { code: 'AR', label: 'Argentina', labelMale: 'Argentino' },
    { code: 'AM', label: 'Armena', labelMale: 'Armeno' },
    { code: 'AU', label: 'Australiana', labelMale: 'Australiano' },
    { code: 'AT', label: 'Austriaca', labelMale: 'Austriaco' },
    { code: 'BR', label: 'Brasiliana', labelMale: 'Brasiliano' },
    { code: 'GB', label: 'Britannica', labelMale: 'Britannico' },
    { code: 'BG', label: 'Bulgara', labelMale: 'Bulgaro' },
    { code: 'KH', label: 'Cambogiana', labelMale: 'Cambogiano' },
    { code: 'CM', label: 'Camerunese' },
    { code: 'CA', label: 'Canadese' },
    { code: 'CL', label: 'Cilena', labelMale: 'Cileno' },
    { code: 'CN', label: 'Cinese' },
    { code: 'CO', label: 'Colombiana', labelMale: 'Colombiano' },
    { code: 'CG', label: 'Congolese' },
    { code: 'KR', label: 'Sudcoreana', labelMale: 'Sudcoreano' },
    { code: 'HR', label: 'Croata' },
    { code: 'CU', label: 'Cubana', labelMale: 'Cubano' },
    { code: 'DK', label: 'Danese' },
    { code: 'EG', label: 'Egiziana', labelMale: 'Egiziano' },
    { code: 'AE', label: 'Emiratina', labelMale: 'Emiratino' },
    { code: 'EC', label: 'Ecuadoriana', labelMale: 'Ecuadoriano' },
    { code: 'ES', label: 'Spagnola', labelMale: 'Spagnolo' },
    { code: 'EE', label: 'Estone' },
    { code: 'FI', label: 'Finlandese' },
    { code: 'GE', label: 'Georgiana', labelMale: 'Georgiano' },
    { code: 'GH', label: 'Ghanese' },
    { code: 'GR', label: 'Greca', labelMale: 'Greco' },
    { code: 'GT', label: 'Guatemalteca', labelMale: 'Guatemalteco' },
    { code: 'HT', label: 'Haitiana', labelMale: 'Haitiano' },
    { code: 'HU', label: 'Ungherese' },
    { code: 'IN', label: 'Indiana', labelMale: 'Indiano' },
    { code: 'ID', label: 'Indonesiana', labelMale: 'Indonesiano' },
    { code: 'IQ', label: 'Irachena', labelMale: 'Iracheno' },
    { code: 'IR', label: 'Iraniana', labelMale: 'Iraniano' },
    { code: 'IE', label: 'Irlandese' },
    { code: 'IS', label: 'Islandese' },
    { code: 'IL', label: 'Israeliana', labelMale: 'Israeliano' },
    { code: 'CI', label: 'Ivoriana', labelMale: 'Ivoriano' },
    { code: 'JP', label: 'Giapponese' },
    { code: 'JO', label: 'Giordana', labelMale: 'Giordano' },
    { code: 'KZ', label: 'Kazaka', labelMale: 'Kazako' },
    { code: 'KE', label: 'Keniota' },
    { code: 'LB', label: 'Libanese' },
    { code: 'LY', label: 'Libica', labelMale: 'Libico' },
    { code: 'LU', label: 'Lussemburghese' },
    { code: 'MK', label: 'Macedone' },
    { code: 'MY', label: 'Malese' },
    { code: 'ML', label: 'Maliana', labelMale: 'Maliano' },
    { code: 'MX', label: 'Messicana', labelMale: 'Messicano' },
    { code: 'MC', label: 'Monegasca', labelMale: 'Monegasco' },
    { code: 'MN', label: 'Mongola', labelMale: 'Mongolo' },
    { code: 'ME', label: 'Montenegrina', labelMale: 'Montenegrino' },
    { code: 'NL', label: 'Olandese' },
    { code: 'NZ', label: 'Neozelandese' },
    { code: 'NE', label: 'Nigerina', labelMale: 'Nigerino' },
    { code: 'NG', label: 'Nigeriana', labelMale: 'Nigeriano' },
    { code: 'NO', label: 'Norvegese' },
    { code: 'PK', label: 'Pakistana', labelMale: 'Pakistano' },
    { code: 'PE', label: 'Peruviana', labelMale: 'Peruviano' },
    { code: 'PH', label: 'Filippina', labelMale: 'Filippino' },
    { code: 'PL', label: 'Polacca', labelMale: 'Polacco' },
    { code: 'PT', label: 'Portoghese' },
    { code: 'QA', label: 'Qatariota' },
    { code: 'RO', label: 'Rumena', labelMale: 'Rumeno' },
    { code: 'RU', label: 'Russa', labelMale: 'Russo' },
    { code: 'SN', label: 'Senegalese' },
    { code: 'RS', label: 'Serba', labelMale: 'Serbo' },
    { code: 'SG', label: 'Singaporiana', labelMale: 'Singaporiano' },
    { code: 'SK', label: 'Slovacca', labelMale: 'Slovacco' },
    { code: 'SI', label: 'Slovena', labelMale: 'Sloveno' },
    { code: 'SE', label: 'Svedese' },
    { code: 'TW', label: 'Taiwanese' },
    { code: 'TD', label: 'Ciadiana', labelMale: 'Ciadiano' },
    { code: 'CZ', label: 'Ceca', labelMale: 'Ceco' },
    { code: 'TH', label: 'Tailandese' },
    { code: 'TR', label: 'Turca', labelMale: 'Turco' },
    { code: 'UA', label: 'Ucraina', labelMale: 'Ucraino' },
    { code: 'UY', label: 'Uruguaiana', labelMale: 'Uruguaiano' },
    { code: 'VE', label: 'Venezuelana', labelMale: 'Venezuelano' },
    { code: 'VN', label: 'Vietnamita' },
  ],
};
